# Generated by Django 3.0.7 on 2020-06-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('name', models.CharField(max_length=50)),
                ('arts', models.CharField(max_length=50)),
                ('descuento', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('contra', models.CharField(max_length=150)),
                ('confir', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
