# Generated by Django 3.0.7 on 2020-06-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsideImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('nombre', models.CharField(max_length=50)),
                ('frase', models.CharField(max_length=50)),
            ],
        ),
    ]
