# Generated by Django 3.0.7 on 2020-06-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20200627_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='likes',
        ),
    ]
