# Generated by Django 3.0.7 on 2020-06-30 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_likesmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikesMarks',
        ),
    ]
