# Generated by Django 3.0.7 on 2020-07-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='slug',
            field=models.SlugField(default='textproduct'),
            preserve_default=False,
        ),
    ]
